name: Docker Build

on:
  workflow_dispatch:

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
  build:
    strategy:
      matrix:
        dir:
          - examples/ui/tailwindcss
          - examples/experimental/wasm

    runs-on: nscloud

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: corepack enable

      - name: Build with Namespace Remote Builders
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            DIR=${{ matrix.dir }}
